### ISSUE TITLE
siuba

### ISSUE THREAD

**Issue by ghuls** [markfairbanks/tidypolars#164]
@markfairbanks FYI: https://github.com/machow/siuba/issues/375 Looks like a quite similar project (but based on pandas).

**Comment by markfairbanks** [comment]
@ghuls Thanks for sending this over. One of the reasons I built tidypolars was because siuba used pandas and it seemed like some people might like tidyverse-like syntax with polars speed instead.

To be honest tidypolars is a pet project since I had never built out a python package. I recommend to people I work with to use polars directly 😄
